sudo: false
language: node_js
node_js:
  - "10"

before_script:
  - npm install -g nyc
  - npm install -g mocha
  - npm install -g coveralls
  - npm run tslint

install:
  - npm install
  - npm run-script build:cli

after_script:
  - npm test
  - npm run-script coverage
