sudo: false
language: node_js
node_js:
  - "10"

before_script:
  - npm install -g nyc typedoc mocha coveralls ts-node
  - npm run-script tslint

install:
  - npm install
  - npm run-script build:cli

after_script:
  - npm run-script doc
  - npm run-script coverage
