sudo: false
language: node_js
node_js:
  - "10"

before_script:
  - npm install -g nyc mocha coveralls

install:
  - cd package/vemsy && npm install
  - cd package/vemsy && npm run-script build

after_script:
  - cd package/vemsy && npm run-script test
